services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: kafka-docker-cluster-1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KARAFKA_ADVERTISED_HOST_NAME: 'kafka'

      # for local development
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      # KARAFKA_ADVERTISED_HOST_NAME: 'kafka'
  db:
    image: postgres:14.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=procare_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RAILS_ENV=development
      - KARAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # for production
      # - DATABASE_URL=postgres://postgres:password@db:5432/procare_production
      #
      # for local development
      # - KARAFKA_BOOTSTRAP_SERVERS=localhost:9092
    develop:
      watch:
        - action: sync
          path: .
          target: /rails
          ignore:
            - .env
    depends_on:
      - kafka
      - db
  consumer:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RAILS_ENV=development
      - KARAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # for production
      # - DATABASE_URL=postgres://postgres:password@db:5432/procare_production
      #
      # for local development
      # - KARAFKA_BOOTSTRAP_SERVERS=localhost:9092
    command: bundle exec karafka server
    expose:
      - "3000"
    depends_on:
      - web
volumes:
  db-data:
